apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redmine

resources:
  - ../../base
  - redmine-ingress.yaml
  - redmine-hpa.yaml
  
patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
